name: Run Cucumber Playwright Tests on Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build docker image
        run: docker build -t playwright-docker .

      - name: Run tests
        run: docker run -v "$(pwd)":/app playwright-docker:latest sh -c "yarn install --frozen-lockfile && yarn test"

      - name: Upload test report - multiple-cucumber-html
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: multiple-cucumber-html-${{ github.run_id }}
          path: reports/html
          retention-days: 30
          compression-level: 9

      - name: Upload test report - cucumber-html
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-${{ github.run_id }}
          path: reports/cucumber-html
          retention-days: 30
          compression-level: 9

      - name: Upload test reports for github pages
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: github-pages-reports-${{ github.run_id }}
          path: reports-history/
          retention-days: 30
          compression-level: 9

  publish-gh-pages:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: reports/

      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          name: github-pages-reports-${{ github.run_id }}
          path: reports/

      - name: Publish HTML report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports
          publish_branch: gh-pages
